# -*- coding: utf-8 -*-
"""AI601_Assignment1_Group-4_Google_Trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGdQlYtvZxsapNRLlsH-UKLCOqtMaEZ-
"""



"""# Part 3: Google Trends"""

!pip install praw pytrends

# %% [code]
import praw
import csv
import pandas as pd
import time
from pytrends.request import TrendReq

"""# Part 3.1: Interest Over Time"""

# Initialize pytrends
pytrends = TrendReq(hl='en-US', tz=360)

# Define keywords
trend_keywords = ["electric vehicle", "tesla", "ev charging"]

# ---------------------------
# Part 1: Interest Over Time
# ---------------------------
# Build the payload for the past 12 months
pytrends.build_payload(trend_keywords, timeframe='today 12-m')

# Get interest over time data
trend_over_time_df = pytrends.interest_over_time()

# Remove the 'isPartial' column if present
if 'isPartial' in trend_over_time_df.columns:
    trend_over_time_df = trend_over_time_df.drop(columns=['isPartial'])

# Reset index to bring the date into a column
trend_over_time_df = trend_over_time_df.reset_index()

# Melt the DataFrame so that each row is: [date, keyword, interest_score]
trend_over_time_melted = trend_over_time_df.melt(id_vars=['date'],
                                                 var_name='keyword',
                                                 value_name='interest_score')

# Save to CSV
trend_over_time_csv = 'google_trends_interest_over_time.csv'
trend_over_time_melted.to_csv(trend_over_time_csv, index=False)
print(f"Interest Over Time data saved to {trend_over_time_csv}.")

"""# Part 3.2: Interest by Region"""

# ---------------------------
# Part 2: Interest by Region
# ---------------------------
# Build the payload again if needed (it uses the same keywords)
pytrends.build_payload(trend_keywords, timeframe='today 12-m')

# Get interest by region data (using 'country' resolution)
trend_by_region_df = pytrends.interest_by_region(resolution='country', inc_low_vol=True)

# Reset index to bring the region names into a column
trend_by_region_df = trend_by_region_df.reset_index()

# Melt the DataFrame so that each row is: [region, keyword, interest_score]
trend_by_region_melted = trend_by_region_df.melt(id_vars=['geoName'],
                                                 var_name='keyword',
                                                 value_name='interest_score')

# Rename 'geoName' to 'region' for clarity
trend_by_region_melted.rename(columns={'geoName': 'region'}, inplace=True)

# Save to CSV
trend_by_region_csv = 'google_trends_interest_by_region.csv'
trend_by_region_melted.to_csv(trend_by_region_csv, index=False)
print(f"Interest by Region data saved to {trend_by_region_csv}.")